config:
  filters:
    - name: product_type
      label: Product Type
      enabled: true
    - name: option1
      label: Color
      enabled: false
    - name: option2
      label: option2
      enabled: false
    - name: option3
      label: option3
      enabled: false
    - name: vendor
      label: vendor
      enabled: false
    - name: tags
      label: tags
      enabled: false
