config:
  filters:
    - name: product_type
      label: Category
      enabled: true
    - name: option1
      label: Material
      enabled: true
    - name: option2
      label: option2
      enabled: true
    - name: option3
      label: optio
      enabled: true
    - name: vendor
      label: vendor
      enabled: true
    - name: tags
      label: tags
      enabled: true
